# Generated by Django 4.1.4 on 2022-12-13 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_delete_doctor_patient_doctor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient", old_name="doctor", new_name="doctors",
        ),
    ]
