# Generated by Django 4.1 on 2022-09-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_record_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(default=None, max_length=6),
            preserve_default=False,
        ),
    ]
