# Generated by Django 4.1 on 2022-09-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_patient_gender"),
    ]

    operations = [
        migrations.RemoveField(model_name="patient", name="gender",),
    ]
