# Generated by Django 4.1 on 2022-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_patient_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="tests",
            field=models.JSONField(default={"BPM": "Not Calculated"}),
        ),
    ]
