# Generated by Django 4.1 on 2022-09-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_record_tests"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="allergies",
            field=models.CharField(default="Not set", max_length=300),
        ),
        migrations.AddField(
            model_name="patient",
            name="habits",
            field=models.CharField(default="Not set", max_length=300),
        ),
        migrations.AddField(
            model_name="patient",
            name="history",
            field=models.CharField(default="Not set", max_length=1000),
        ),
        migrations.AddField(
            model_name="patient",
            name="medicines",
            field=models.CharField(default="Not set", max_length=300),
        ),
    ]
