# Generated by Django 4.1.4 on 2022-12-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_record_doctor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="read_status",
            field=models.BooleanField(default=False),
        ),
    ]
