# Generated by Django 4.1 on 2022-09-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_patient_allergies_patient_habits_patient_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="blood",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
