# Generated by Django 4.1.4 on 2023-05-08 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_dailypatients"),
    ]

    operations = [
        migrations.RemoveField(model_name="patient", name="age",),
        migrations.AddField(
            model_name="patient",
            name="birthday",
            field=models.DateField(default=datetime.datetime(1980, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
