# Generated by Django 4.1 on 2022-09-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_record_outcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="description",
            field=models.CharField(default="Not set", max_length=1500),
        ),
        migrations.AlterField(
            model_name="record", name="reason", field=models.CharField(max_length=100),
        ),
    ]
