# Generated by Django 4.1 on 2022-09-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_record_description_alter_record_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="description",
            field=models.CharField(default="Not set", max_length=3000),
        ),
        migrations.AlterField(
            model_name="record",
            name="outcome",
            field=models.CharField(default="Not set", max_length=3000),
        ),
    ]
