# Generated by Django 4.1 on 2022-09-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_record_description_alter_record_outcome"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record", old_name="outcome", new_name="diagnosis",
        ),
        migrations.AddField(
            model_name="record",
            name="notes",
            field=models.CharField(default="Not set", max_length=3000),
        ),
        migrations.AlterField(
            model_name="patient",
            name="blood",
            field=models.CharField(
                blank=True, default="Not set", max_length=10, null=True
            ),
        ),
    ]
