# Generated by Django 4.1 on 2022-10-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_record_tests"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
