# Generated by Django 4.1 on 2022-10-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_record_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="tests",
            field=models.JSONField(
                default={"lab": {"verified": False}, "radiology": {"verified": False}}
            ),
        ),
    ]
